# ===============================
# 分类与映射配置
CHANNEL_CATEGORIES = {
    "央视频道": [
        "CCTV1", "CCTV2", "CCTV3", "CCTV4", "CCTV4欧洲", "CCTV4美洲", "CCTV5", "CCTV5+", "CCTV6", "CCTV7",
        "CCTV8", "CCTV9", "CCTV10", "CCTV11", "CCTV12", "CCTV13", "CCTV14", "CCTV15", "CCTV16", "CCTV17", "CCTV4K", "CCTV8K",
        "兵器科技", "风云音乐", "风云足球", "风云剧场", "怀旧剧场", "第一剧场", "女性时尚", "世界地理", "央视台球", "高尔夫网球",
        "央视文化精品", "卫生健康", "电视指南", "中学生", "发现之旅", "书法频道", "国学频道", "环球奇观"
    ],
    "卫视频道": [
        "湖南卫视", "浙江卫视", "江苏卫视", "东方卫视", "深圳卫视", "北京卫视", "广东卫视", "广西卫视", "东南卫视", "海南卫视",
        "河北卫视", "河南卫视", "湖北卫视", "江西卫视", "四川卫视", "重庆卫视", "贵州卫视", "云南卫视", "天津卫视", "安徽卫视",
        "山东卫视", "辽宁卫视", "黑龙江卫视", "吉林卫视", "内蒙古卫视", "宁夏卫视", "山西卫视", "陕西卫视", "甘肃卫视", "青海卫视",
        "新疆卫视", "西藏卫视", "三沙卫视", "兵团卫视", "延边卫视", "安多卫视", "康巴卫视", "农林卫视", "山东教育卫视",
        "中国教育1台", "中国教育2台", "中国教育3台", "中国教育4台", "早期教育"
    ],
    "数字频道": [
        "CHC动作电影", "CHC家庭影院", "CHC影迷电影", "淘电影", "淘精彩", "淘剧场", "淘4K", "淘娱乐", "淘BABY", "淘萌宠", "重温经典",
        "星空卫视", "CHANNEL[V]", "凤凰卫视中文台", "凤凰卫视资讯台", "凤凰卫视香港台", "凤凰卫视电影台", "求索纪录", "求索科学",
        "求索生活", "求索动物", "纪实人文", "金鹰纪实", "纪实科教", "睛彩青少", "睛彩竞技", "睛彩篮球", "睛彩广场舞", "魅力足球", "五星体育",
        "劲爆体育", "快乐垂钓", "茶频道", "先锋乒羽", "天元围棋", "汽摩", "梨园频道", "文物宝库", "武术世界", "哒啵赛事", "哒啵电竞", "黑莓电影", "黑莓动画", 
        "乐游", "生活时尚", "都市剧场", "欢笑剧场", "游戏风云", "金色学堂", "动漫秀场", "新动漫", "卡酷少儿", "金鹰卡通", "优漫卡通", "哈哈炫动", "嘉佳卡通", 
        "中国交通", "中国天气", "华数4K", "华数星影", "华数动作影院", "华数喜剧影院", "华数家庭影院", "华数经典电影", "华数热播剧场", "华数碟战剧场",
        "华数军旅剧场", "华数城市剧场", "华数武侠剧场", "华数古装剧场", "华数魅力时尚", "华数少儿动画", "华数动画"
    ],
    "湖北": [
        "湖北公共新闻", "湖北经视频道", "湖北综合频道", "湖北垄上频道", "湖北影视频道", "湖北生活频道", "湖北教育频道", "武汉新闻综合", "武汉电视剧", "武汉科技生活",
        "武汉文体频道", "武汉教育频道", "阳新综合", "房县综合", "蔡甸综合",
    ],#任意添加，与仓库中rtp/省份运营商.txt内频道一致即可，或在下方频道名映射中改名
}

# ===== 映射（别名 -> 标准名） =====
CHANNEL_MAPPING = {
    "CCTV1": ["CCTV-1", "CCTV-1 HD", "CCTV1 HD", "CCTV-1综合"],
    "CCTV2": ["CCTV-2", "CCTV-2 HD", "CCTV2 HD", "CCTV-2财经"],
    "CCTV3": ["CCTV-3", "CCTV-3 HD", "CCTV3 HD", "CCTV-3综艺"],
    "CCTV4": ["CCTV-4", "CCTV-4 HD", "CCTV4 HD", "CCTV-4中文国际"],
    "CCTV4欧洲": ["CCTV-4欧洲", "CCTV-4欧洲", "CCTV4欧洲 HD", "CCTV-4 欧洲", "CCTV-4中文国际欧洲", "CCTV4中文欧洲"],
    "CCTV4美洲": ["CCTV-4美洲", "CCTV-4北美", "CCTV4美洲 HD", "CCTV-4 美洲", "CCTV-4中文国际美洲", "CCTV4中文美洲"],
    "CCTV5": ["CCTV-5", "CCTV-5 HD", "CCTV5 HD", "CCTV-5体育"],
    "CCTV5+": ["CCTV-5+", "CCTV-5+ HD", "CCTV5+ HD", "CCTV-5+体育赛事"],
    "CCTV6": ["CCTV-6", "CCTV-6 HD", "CCTV6 HD", "CCTV-6电影"],
    "CCTV7": ["CCTV-7", "CCTV-7 HD", "CCTV7 HD", "CCTV-7国防军事"],
    "CCTV8": ["CCTV-8", "CCTV-8 HD", "CCTV8 HD", "CCTV-8电视剧"],
    "CCTV9": ["CCTV-9", "CCTV-9 HD", "CCTV9 HD", "CCTV-9纪录"],
    "CCTV10": ["CCTV-10", "CCTV-10 HD", "CCTV10 HD", "CCTV-10科教"],
    "CCTV11": ["CCTV-11", "CCTV-11 HD", "CCTV11 HD", "CCTV-11戏曲"],
    "CCTV12": ["CCTV-12", "CCTV-12 HD", "CCTV12 HD", "CCTV-12社会与法"],
    "CCTV13": ["CCTV-13", "CCTV-13 HD", "CCTV13 HD", "CCTV-13新闻"],
    "CCTV14": ["CCTV-14", "CCTV-14 HD", "CCTV14 HD", "CCTV-14少儿"],
    "CCTV15": ["CCTV-15", "CCTV-15 HD", "CCTV15 HD", "CCTV-15音乐"],
    "CCTV16": ["CCTV-16", "CCTV-16 HD", "CCTV-16 4K", "CCTV-16奥林匹克", "CCTV16 4K", "CCTV-16奥林匹克4K"],
    "CCTV17": ["CCTV-17", "CCTV-17 HD", "CCTV17 HD", "CCTV-17农业农村"],
    "CCTV4K": ["CCTV4K超高清", "CCTV-4K超高清", "CCTV-4K 超高清", "CCTV 4K"],
    "CCTV8K": ["CCTV8K超高清", "CCTV-8K超高清", "CCTV-8K 超高清", "CCTV 8K"],
    "兵器科技": ["CCTV-兵器科技", "CCTV兵器科技"],
    "风云音乐": ["CCTV-风云音乐", "CCTV风云音乐"],
    "第一剧场": ["CCTV-第一剧场", "CCTV第一剧场"],
    "风云足球": ["CCTV-风云足球", "CCTV风云足球"],
    "风云剧场": ["CCTV-风云剧场", "CCTV风云剧场"],
    "怀旧剧场": ["CCTV-怀旧剧场", "CCTV怀旧剧场"],
    "女性时尚": ["CCTV-女性时尚", "CCTV女性时尚"],
    "世界地理": ["CCTV-世界地理", "CCTV世界地理"],
    "央视台球": ["CCTV-央视台球", "CCTV央视台球"],
    "高尔夫网球": ["CCTV-高尔夫网球", "CCTV高尔夫网球", "CCTV央视高网", "CCTV-高尔夫·网球", "央视高网"],
    "央视文化精品": ["CCTV-央视文化精品", "CCTV央视文化精品", "CCTV文化精品", "CCTV-文化精品", "文化精品"],
    "卫生健康": ["CCTV-卫生健康", "CCTV卫生健康"],
    "电视指南": ["CCTV-电视指南", "CCTV电视指南"],
    "农林卫视": ["陕西农林卫视"],
    "三沙卫视": ["海南三沙卫视"],
    "兵团卫视": ["新疆兵团卫视"],
    "延边卫视": ["吉林延边卫视"],
    "安多卫视": ["青海安多卫视"],
    "康巴卫视": ["四川康巴卫视"],
    "山东教育卫视": ["山东教育"],
    "中国教育1台": ["CETV1", "中国教育一台", "中国教育1", "CETV-1 综合教育", "CETV-1"],
    "中国教育2台": ["CETV2", "中国教育二台", "中国教育2", "CETV-2 空中课堂", "CETV-2"],
    "中国教育3台": ["CETV3", "中国教育三台", "中国教育3", "CETV-3 教育服务", "CETV-3"],
    "中国教育4台": ["CETV4", "中国教育四台", "中国教育4", "CETV-4 职业教育", "CETV-4"],
    "早期教育": ["中国教育5台", "中国教育五台", "CETV早期教育", "华电早期教育", "CETV 早期教育"],
    "湖南卫视": ["湖南卫视4K"],
    "北京卫视": ["北京卫视4K"],
    "东方卫视": ["东方卫视4K"],
    "广东卫视": ["广东卫视4K"],
    "深圳卫视": ["深圳卫视4K"],
    "山东卫视": ["山东卫视4K"],
    "四川卫视": ["四川卫视4K"],
    "浙江卫视": ["浙江卫视4K"],
    "CHC影迷电影": ["CHC高清电影", "CHC-影迷电影", "影迷电影", "chc高清电影"],
    "淘电影": ["IPTV淘电影", "北京IPTV淘电影", "北京淘电影"],
    "淘精彩": ["IPTV淘精彩", "北京IPTV淘精彩", "北京淘精彩"],
    "淘剧场": ["IPTV淘剧场", "北京IPTV淘剧场", "北京淘剧场"],
    "淘4K": ["IPTV淘4K", "北京IPTV4K超清", "北京淘4K", "淘4K", "淘 4K"],
    "淘娱乐": ["IPTV淘娱乐", "北京IPTV淘娱乐", "北京淘娱乐"],
    "淘BABY": ["IPTV淘BABY", "北京IPTV淘BABY", "北京淘BABY", "IPTV淘baby", "北京IPTV淘baby", "北京淘baby"],
    "淘萌宠": ["IPTV淘萌宠", "北京IPTV萌宠TV", "北京淘萌宠"],
    "魅力足球": ["上海魅力足球"],
    "睛彩青少": ["睛彩羽毛球"],
    "求索纪录": ["求索记录", "求索纪录4K", "求索记录4K", "求索纪录 4K", "求索记录 4K"],
    "金鹰纪实": ["湖南金鹰纪实", "金鹰记实"],
    "纪实科教": ["北京纪实科教", "BRTV纪实科教", "纪实科教8K"],
    "星空卫视": ["星空衛視", "星空衛视", "星空卫視"],
    "CHANNEL[V]": ["CHANNEL-V", "Channel[V]"],
    "凤凰卫视中文台": ["凤凰中文", "凤凰中文台", "凤凰卫视中文", "凤凰卫视"],
    "凤凰卫视香港台": ["凤凰香港台", "凤凰卫视香港", "凤凰香港"],
    "凤凰卫视资讯台": ["凤凰资讯", "凤凰资讯台", "凤凰咨询", "凤凰咨询台", "凤凰卫视咨询台", "凤凰卫视资讯", "凤凰卫视咨询"],
    "凤凰卫视电影台": ["凤凰电影", "凤凰电影台", "凤凰卫视电影", "鳳凰衛視電影台", " 凤凰电影"],
    "茶频道": ["湖南茶频道"],
    "快乐垂钓": ["湖南快乐垂钓"],
    "先锋乒羽": ["湖南先锋乒羽"],
    "天元围棋": ["天元围棋频道"],
    "汽摩": ["重庆汽摩", "汽摩频道", "重庆汽摩频道"],
    "梨园频道": ["河南梨园频道", "梨园", "河南梨园"],
    "文物宝库": ["河南文物宝库"],
    "武术世界": ["河南武术世界"],
    "乐游": ["乐游频道", "上海乐游频道", "乐游纪实", "SiTV乐游频道", "SiTV 乐游频道"],
    "欢笑剧场": ["上海欢笑剧场4K", "欢笑剧场 4K", "欢笑剧场4K", "上海欢笑剧场"],
    "生活时尚": ["生活时尚4K", "SiTV生活时尚", "上海生活时尚"],
    "都市剧场": ["都市剧场4K", "SiTV都市剧场", "上海都市剧场"],
    "游戏风云": ["游戏风云4K", "SiTV游戏风云", "上海游戏风云"],
    "金色学堂": ["金色学堂4K", "SiTV金色学堂", "上海金色学堂"],
    "动漫秀场": ["动漫秀场4K", "SiTV动漫秀场", "上海动漫秀场"],
    "卡酷少儿": ["北京KAKU少儿", "BRTV卡酷少儿", "北京卡酷少儿", "卡酷动画"],
    "哈哈炫动": ["炫动卡通", "上海哈哈炫动"],
    "优漫卡通": ["江苏优漫卡通", "优漫漫画"],
    "金鹰卡通": ["湖南金鹰卡通"],
    "中国交通": ["中国交通频道"],
    "中国天气": ["中国天气频道"],
    "华数4K": ["华数低于4K", "华数4K电影", "华数爱上4K"],
}#格式为"频道分类中的标准名": ["rtp/中的名字"],


# ===============================
# tvg-name 到 tvg-logo 的映射
# 从 m3u 目录中的所有 m3u 文件中自动提取
TVG_NAME_LOGO_MAPPING = {
    "4K电影": "https://epg.112114.xyz/logo/4K电影.png",
    "4K超清": "https://epg.112114.xyz/logo/4K超清.png",
    "BTV影视": "https://epg.112114.xyz/logo/BTV影视.png",
    "BTV文艺": "https://epg.112114.xyz/logo/BTV文艺.png",
    "BTV新闻": "https://epg.112114.xyz/logo/BTV新闻.png",
    "BTV生活": "https://epg.112114.xyz/logo/BTV生活.png",
    "BTV科教": "https://epg.112114.xyz/logo/BTV科教.png",
    "BTV财经": "https://epg.112114.xyz/logo/BTV财经.png",
    "BTV青年": "https://epg.112114.xyz/logo/BTV青年.png",
    "BestTV测试1-4K": "https://live.fanmingming.com/tv/百事通.png",
    "BestTV测试2-4K": "https://live.fanmingming.com/tv/百事通.png",
    "BestTV测试3-4K": "https://live.fanmingming.com/tv/百事通.png",
    "CCTV1": "https://live.fanmingming.com/tv/CCTV1.png",
    "CCTV1(备)": "https://live.fanmingming.com/tv/CCTV1.png",
    "CCTV10": "https://live.fanmingming.com/tv/CCTV10.png",
    "CCTV11": "https://live.fanmingming.com/tv/CCTV11.png",
    "CCTV12": "https://live.fanmingming.com/tv/CCTV12.png",
    "CCTV13": "https://live.fanmingming.com/tv/CCTV13.png",
    "CCTV14": "https://live.fanmingming.com/tv/CCTV14.png",
    "CCTV15": "https://live.fanmingming.com/tv/CCTV15.png",
    "CCTV16": "https://live.fanmingming.com/tv/CCTV16.png",
    "CCTV16-4K": "https://live.fanmingming.com/tv/CCTV16.png",
    "CCTV16-4K(备)": "https://live.fanmingming.com/tv/CCTV16.png",
    "CCTV17": "https://live.fanmingming.com/tv/CCTV17.png",
    "CCTV2": "https://live.fanmingming.com/tv/CCTV2.png",
    "CCTV3": "https://live.fanmingming.com/tv/CCTV3.png",
    "CCTV4": "https://live.fanmingming.com/tv/CCTV4.png",
    "CCTV4AME": "https://epg.112114.xyz/logo/CCTV4AME.png",
    "CCTV4EUO": "https://epg.112114.xyz/logo/CCTV4EUO.png",
    "CCTV4K": "https://epg.112114.xyz/logo/CCTV4K.png",
    "CCTV4欧洲": "https://epg.112114.xyz/logo/CCTV4欧洲.png",
    "CCTV4美洲": "https://epg.112114.xyz/logo/CCTV4美洲.png",
    "CCTV5": "https://live.fanmingming.com/tv/CCTV5.png",
    "CCTV5+": "https://live.fanmingming.com/tv/CCTV5+.png",
    "CCTV6": "https://live.fanmingming.com/tv/CCTV6.png",
    "CCTV7": "https://live.fanmingming.com/tv/CCTV7.png",
    "CCTV8": "https://live.fanmingming.com/tv/CCTV8.png",
    "CCTV9": "https://live.fanmingming.com/tv/CCTV9.png",
    "CETV1": "https://kakaxi-1.asia/LOGO/CETV1.png",
    "CETV2": "https://kakaxi-1.asia/LOGO/CETV2.png",
    "CETV4": "https://kakaxi-1.asia/LOGO/CETV4.png",
    "CGTN": "https://live.fanmingming.com/tv/CGTN.png",
    "CGTN俄语": "https://epg.112114.xyz/logo/CGTN俄语.png",
    "CGTN法语": "https://live.fanmingming.com/tv/CGTN法语.png",
    "CGTN西班牙语": "https://live.fanmingming.com/tv/CGTN西语.png",
    "CGTN记录片": "https://live.fanmingming.com/tv/CGTN纪录.png",
    "CGTN阿拉伯语": "https://epg.112114.xyz/logo/CGTN阿拉伯语.png",
    "CHC动作电影": "https://live.fanmingming.com/tv/CHC动作电影.png",
    "CHC家庭影院": "https://epg.112114.xyz/logo/CHC家庭影院.png",
    "CHC影迷电影": "https://live.fanmingming.com/tv/CHC高清电影.png",
    "IPTV少儿动画": "https://epg.112114.xyz/logo/IPTV少儿动画.png",
    "IPTV热播剧场": "https://epg.112114.xyz/logo/IPTV热播剧场.png",
    "IPTV经典电影": "https://epg.112114.xyz/logo/IPTV经典电影.png",
    "NewTV动作电影": "https://epg.112114.xyz/logo/NewTV动作电影.png",
    "NewTV惊悚悬疑": "https://epg.112114.xyz/logo/NewTV惊悚悬疑.png",
    "NewTV超级电影": "https://epg.112114.xyz/logo/NewTV超级电影.png",
    "三沙卫视": "http://epg.51zmt.top:8000/tb1/ws/sansha.png",
    "上海纪实": "https://epg.112114.xyz/logo/上海纪实.png",
    "世界地理": "https://live.fanmingming.com/tv/世界地理.png",
    "东南卫视": "https://live.fanmingming.com/tv/东南卫视.png",
    "东方卫视": "https://live.fanmingming.com/tv/东方卫视.png",
    "东方卫视(备)": "https://live.fanmingming.com/tv/东方卫视.png",
    "东方财经": "https://kakaxi-1.asia/LOGO/东方财经.png",
    "中国交通": "https://kakaxi-1.asia/LOGO/中国交通.png",
    "中国交通频道": "https://epg.112114.xyz/logo/中国交通频道.png",
    "中国教育1台": "https://live.fanmingming.com/tv/CETV1.png",
    "中国教育2台": "http://epg.51zmt.top:8000/tb1/qt/中国教育2台.png",
    "中国教育3台": "https://epg.112114.xyz/logo/中国教育3台.png",
    "中国教育4台": "http://epg.51zmt.top:8000/tb1/qt/中国教育4台.png",
    "中学生": "https://kakaxi-1.asia/LOGO/中学生.png",
    "乐游": "https://kakaxi-1.asia/LOGO/乐游.png",
    "书画": "https://kakaxi-1.asia/LOGO/书画.png",
    "书画频道": "http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE37.jpg",
    "云南卫视": "http://epg.51zmt.top:8000/tb1/ws/yunnan.png",
    "先锋乒羽": "http://epg.51zmt.top:8000/tb1/qt/XFBY.png",
    "光影": "https://epg.112114.xyz/logo/光影.png",
    "全纪实": "https://epg.112114.xyz/logo/全纪实.png",
    "兵器科技": "https://live.fanmingming.com/tv/兵器科技.png",
    "兵团卫视": "http://epg.51zmt.top:8000/tb1/ws/bingtuan.png",
    "内蒙古卫视": "http://epg.51zmt.top:8000/tb1/ws/neimeng.png",
    "军事": "https://epg.112114.xyz/logo/军事.png",
    "军旅剧场": "https://epg.112114.xyz/logo/军旅剧场.png",
    "凤凰中文": "https://kakaxi-1.asia/LOGO/凤凰中文.png",
    "凤凰资讯": "https://kakaxi-1.asia/LOGO/凤凰资讯.png",
    "动作影院": "https://epg.112114.xyz/logo/动作影院.png",
    "动作电影": "https://epg.112114.xyz/logo/动作电影.png",
    "动漫秀场": "https://kakaxi-1.asia/LOGO/动漫秀场.png",
    "动画": "https://epg.112114.xyz/logo/动画.png",
    "北京卫视": "https://live.fanmingming.com/tv/北京卫视.png",
    "南方卫视": "https://epg.112114.xyz/logo/南方卫视.png",
    "卡酷动画": "https://epg.112114.xyz/logo/卡酷动画.png",
    "卡酷少儿": "https://live.fanmingming.com/tv/卡酷少儿.png",
    "卫生健康": "https://epg.112114.xyz/logo/卫生健康.png",
    "厦门卫视": "https://epg.112114.xyz/logo/厦门卫视.png",
    "古装剧场": "https://epg.112114.xyz/logo/古装剧场.png",
    "台球": "https://epg.112114.xyz/logo/台球.png",
    "吉林卫视": "https://live.fanmingming.com/tv/吉林卫视.png",
    "哈哈炫动": "https://kakaxi-1.asia/LOGO/哈哈炫动.png",
    "喜剧影院": "https://epg.112114.xyz/logo/喜剧影院.png",
    "嘉佳卡通": "https://epg.112114.xyz/logo/嘉佳卡通.png",
    "四川卫视": "https://live.fanmingming.com/tv/四川卫视.png",
    "四海钓鱼": "https://kakaxi-1.asia/LOGO/四海钓鱼.png",
    "国学": "https://epg.112114.xyz/logo/国学.png",
    "地理": "https://epg.112114.xyz/logo/地理.png",
    "城市剧场": "https://epg.112114.xyz/logo/城市剧场.png",
    "墨宝": "https://epg.112114.xyz/logo/墨宝.png",
    "大健康": "https://epg.112114.xyz/logo/大健康.png",
    "天津卫视": "https://live.fanmingming.com/tv/天津卫视.png",
    "央视台球": "https://live.fanmingming.com/tv/央视台球.png",
    "女性时尚": "https://kakaxi-1.asia/LOGO/女性时尚.png",
    "好学生": "https://epg.112114.xyz/logo/好学生.png",
    "宁夏卫视": "http://epg.51zmt.top:8000/tb1/ws/ningxia.png",
    "安徽卫视": "https://live.fanmingming.com/tv/安徽卫视.png",
    "家庭影院": "https://epg.112114.xyz/logo/家庭影院.png",
    "山东卫视": "https://live.fanmingming.com/tv/山东卫视.png",
    "山东教育": "https://epg.112114.xyz/logo/山东教育.png",
    "山西卫视": "http://epg.51zmt.top:8000/tb1/ws/shanxi_.png",
    "广东卫视": "https://live.fanmingming.com/tv/广东卫视.png",
    "广西卫视": "https://live.fanmingming.com/tv/广西卫视.png",
    "康巴卫视": "https://kakaxi-1.asia/LOGO/康巴卫视.png",
    "延庆电视台": "https://epg.112114.xyz/logo/延庆电视台.png",
    "延边卫视": "https://kakaxi-1.asia/LOGO/延边卫视.png",
    "快乐垂钓": "https://live.fanmingming.com/tv/快乐垂钓.png",
    "怀旧剧场": "https://kakaxi-1.asia/LOGO/怀旧剧场.png",
    "戏曲": "https://epg.112114.xyz/logo/戏曲.png",
    "房县综合": "https://epg.112114.xyz/logo/房县新闻综合.png",
    "收视指南": "https://epg.112114.xyz/logo/收视指南.png",
    "文物宝库": "https://kakaxi-1.asia/LOGO/文物宝库.png",
    "新动漫": "https://kakaxi-1.asia/LOGO/新动漫.png",
    "新疆卫视": "http://epg.51zmt.top:8000/tb1/ws/xinjiang.png",
    "旅游卫视": "https://epg.112114.xyz/logo/旅游卫视.png",
    "早教": "https://epg.112114.xyz/logo/早教.png",
    "星影": "https://epg.112114.xyz/logo/星影.png",
    "朝阳融媒": "https://epg.112114.xyz/logo/朝阳融媒.png",
    "梨园": "https://kakaxi-1.asia/LOGO/梨园频道.png",
    "梨园频道": "https://live.fanmingming.com/tv/河南梨园.png",
    "欢笑剧场": "https://kakaxi-1.asia/LOGO/欢笑剧场.png",
    "武侠剧场": "https://epg.112114.xyz/logo/武侠剧场.png",
    "武术": "https://epg.112114.xyz/logo/武术.png",
    "武术世界": "https://live.fanmingming.com/tv/武术世界.png",
    "武汉五台": "https://epg.112114.xyz/logo/武汉文体.png",
    "武汉六台": "https://epg.112114.xyz/logo/武汉外语.png",
    "武汉四台": "https://epg.112114.xyz/logo/武汉经济.png",
    "武汉外语频道": "http://epg.51zmt.top:8000/tb1/qt/WHTV6.png",
    "武汉少儿频道": "http://epg.51zmt.top:8000/tb1/qt/WHTV7.png",
    "武汉教育": "https://epg.112114.xyz/logo/武汉教育.png",
    "武汉新闻综合": "https://epg.112114.xyz/logo/武汉新闻综合.png",
    "武汉电视剧": "https://epg.112114.xyz/logo/武汉电视剧.png",
    "武汉科技生活": "https://epg.112114.xyz/logo/武汉科技生活.png",
    "武汉经济频道": "http://epg.51zmt.top:8000/tb1/qt/WHTV4.png",
    "求索动物": "https://epg.112114.xyz/logo/求索动物.png",
    "求索科学": "https://epg.112114.xyz/logo/求索科学.png",
    "求索记录": "https://epg.112114.xyz/logo/求索记录.png",
    "江苏卫视": "https://live.fanmingming.com/tv/江苏卫视.png",
    "江苏卫视(备)": "https://live.fanmingming.com/tv/江苏卫视.png",
    "江西卫视": "https://live.fanmingming.com/tv/江西卫视.png",
    "汽摩": "https://kakaxi-1.asia/LOGO/汽摩.png",
    "河北卫视": "https://live.fanmingming.com/tv/河北卫视.png",
    "河北卫视(备)": "https://live.fanmingming.com/tv/河北卫视.png",
    "河南卫视": "https://live.fanmingming.com/tv/河南卫视.png",
    "法治天地": "https://kakaxi-1.asia/LOGO/法治天地.png",
    "浙江卫视": "https://live.fanmingming.com/tv/浙江卫视.png",
    "海南卫视": "https://live.fanmingming.com/tv/海南卫视.png",
    "淘剧场": "https://epg.112114.xyz/logo/淘剧场.png",
    "淘娱乐": "https://epg.112114.xyz/logo/淘娱乐.png",
    "淘电影": "https://epg.112114.xyz/logo/淘电影.png",
    "淘精彩": "https://epg.112114.xyz/logo/淘精彩.png",
    "深圳卫视": "https://live.fanmingming.com/tv/深圳卫视.png",
    "游戏风云": "https://kakaxi-1.asia/LOGO/游戏风云.png",
    "湖北公共新闻": "https://epg.112114.xyz/logo/湖北公共新闻1.png",
    "湖北卫视": "https://live.fanmingming.com/tv/湖北卫视.png",
    "湖北垄上": "https://epg.112114.xyz/logo/湖北垄上.png",
    "湖北影视": "https://epg.112114.xyz/logo/湖北影视.png",
    "湖北教育": "https://epg.112114.xyz/logo/湖北教育.png",
    "湖北生活": "https://epg.112114.xyz/logo/湖北生活.png",
    "湖北经视": "https://epg.112114.xyz/logo/湖北经视.png",
    "湖北综合": "https://epg.112114.xyz/logo/湖北综合.png",
    "湖南卫视": "https://live.fanmingming.com/tv/湖南卫视.png",
    "爱上4K": "https://live.fanmingming.com/tv/爱上4K.png",
    "爱旅行": "https://epg.112114.xyz/logo/爱旅行.png",
    "爱生活": "https://epg.112114.xyz/logo/爱生活.png",
    "爱科学": "https://epg.112114.xyz/logo/爱科学.png",
    "爱院线": "https://epg.112114.xyz/logo/爱院线.png",
    "环球奇观": "https://kakaxi-1.asia/LOGO/环球奇观.png",
    "甘肃卫视": "https://epg.112114.xyz/logo/甘肃卫视.png",
    "生活时尚": "https://kakaxi-1.asia/LOGO/生活时尚.png",
    "电视指南": "https://kakaxi-1.asia/LOGO/电视指南.png",
    "睛彩广场舞": "https://epg.112114.xyz/logo/睛彩广场舞.png",
    "睛彩竞技": "https://epg.112114.xyz/logo/睛彩竞技.png",
    "睛彩篮球": "https://epg.112114.xyz/logo/睛彩篮球.png",
    "睛彩羽毛球": "https://epg.112114.xyz/logo/睛彩羽毛球.png",
    "睛彩青少": "https://kakaxi-1.asia/LOGO/睛彩青少.png",
    "第一剧场": "https://live.fanmingming.com/tv/第一剧场.png",
    "精品记录": "https://epg.112114.xyz/logo/精品记录.png",
    "精选": "https://epg.112114.xyz/logo/精选.png",
    "美人": "https://epg.112114.xyz/logo/美人.png",
    "美妆": "https://epg.112114.xyz/logo/美妆.png",
    "老故事": "http://epg.51zmt.top:8000/tb1/CCTV/CCTVlaogushi.png",
    "茶频道": "https://live.fanmingming.com/tv/茶.png",
    "萌宠TV": "https://epg.112114.xyz/logo/萌宠TV.png",
    "蔡甸综合": "https://epg.112114.xyz/logo/蔡甸综合.png",
    "西藏卫视": "https://epg.112114.xyz/logo/西藏卫视.png",
    "解密": "https://epg.112114.xyz/logo/解密.png",
    "财富天下": "http://epg.51zmt.top:8000/tb1/qt/财富天下.png",
    "贵州卫视": "https://live.fanmingming.com/tv/贵州卫视.png",
    "足球": "https://epg.112114.xyz/logo/足球.png",
    "辽宁卫视": "https://live.fanmingming.com/tv/辽宁卫视.png",
    "都市剧场": "https://kakaxi-1.asia/LOGO/都市剧场.png",
    "重庆卫视": "https://live.fanmingming.com/tv/重庆卫视.png",
    "金色学堂": "https://kakaxi-1.asia/LOGO/金色学堂.png",
    "金鹰卡通": "https://live.fanmingming.com/tv/金鹰卡通.png",
    "金鹰纪实": "https://live.fanmingming.com/tv/金鹰纪实.png",
    "鉴赏": "https://epg.112114.xyz/logo/鉴赏.png",
    "阳新综合": "https://epg.112114.xyz/logo/HUANGSI.png",
    "陕西卫视": "http://epg.51zmt.top:8000/tb1/ws/shanxi.png",
    "青海卫视": "http://epg.51zmt.top:8000/tb1/ws/qinghai.png",
    "音乐现场": "https://epg.112114.xyz/logo/音乐现场.png",
    "风云足球": "https://live.fanmingming.com/tv/风云足球.png",
    "风云音乐": "http://epg.51zmt.top:8000/tb1/CCTV/CCTVfengyunyinyue.png",
    "高尔夫网球": "https://live.fanmingming.com/tv/高尔夫网球.png",
    "高网": "https://epg.112114.xyz/logo/高网.png",
    "魅力时尚": "https://epg.112114.xyz/logo/魅力时尚.png",
    "魅力足球": "https://kakaxi-1.asia/LOGO/魅力足球.png",
    "黑莓电影": "https://epg.112114.xyz/logo/黑莓电影.png",
    "黑龙江卫视": "https://live.fanmingming.com/tv/黑龙江卫视.png",
}
